name: Run unit tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check-out our repository under $GITHUB_WORKSPACE, so our job can access it
        uses: actions/checkout@v2

      # If you use this, you need to pull the remote repository after each build,
      # which basically means after each push.
      - name: Change a file and push it to the repository.
        run: |
          date >> updated/generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "generated"
          git push
